version: "3"

services:

  # TODO add MongoDB

  nosql-javaee:
    build:
      context: .
    image: nosql-javaee:1.0.1
    ports:
    - "8080:8080"
    networks:
    - jee8net

networks:
  jee8net:
    driver: bridge
