version: "3"

services:

  tracing-service:
    build:
      context: .
    image: tracing-service:1.0.1
    ports:
    - "8080:8080"
    networks:
    - jee8net

networks:
  jee8net:
    driver: bridge
