version: "3"

services:

  # TODO add CockroachDB

  cloud-native-jpa:
    build:
      context: .
    image: cloud-native-jpa:1.0.1
    ports:
    - "18080:8080"
    networks:
    - jee8net

networks:
  jee8net:
    driver: bridge

volumes:
  data-volume1:
  data-volume2:
  data-volume3: