version: "3"

services:

  # add message queue here

  messaging-service:
    build:
      context: .
    image: messaging-service:1.0.1
    ports:
    - "8080:8080"
    depends_on:
    - message-queue
    networks:
    - jee8net
    labels:
      kompose.service.type: loadbalancer
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 640M
        reservations:
          memory: 640M

networks:
  jee8net:
    driver: bridge
