apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: health-service
  name: health-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: health-service
    spec:
      containers:
      - image: health-service:1.0.1
        name: health-service
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 640Mi
          requests:
            memory: 640Mi

        # TODO add readiness and liveness probes